singleTypes:
    - id: about
      directory: /content/home
      fileName: about
      fileExtension: md
      mainContent: bioText
    - id: guestArticles
      directory: /content/home
      fileName: guestarticles
      fileExtension: md
      mainContent: GuestArticlesText
