version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.72
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: sudo apt update && sudo apt install git nodejs npm -qy

      # checkout the repository
      - checkout

      - run:
          name: Checkout Submodules if Needed
          command: |
            if [ -f ".gitmodules" ]; then
              git submodule sync
              git submodule update --force --recursive --init --remote
            fi

   # build with Hugo
      - run: hugo version
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: test our generated HTML files
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external

      - deploy:
          name: Deploy
          command: cd $HUGO_BUILD_DIR && find . -type f -exec curl -u ${username}:${password} ${ssl} --ssl-reqd --ftp-create-dirs -T {} ftp://${host}/{} \;
