version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install Hugo
          command: apt-get update && apt-get install curl hugo -qy

      - run:
          name: Generate Static Content
          command: hugo

      - run:
          name: Deploy
          command: find . -type f -exec curl -u ${username}:${password} ${ssl} --ssl-reqd --ftp-create-dirs -T {} ftp://${host}/{} \;
