version: 2.1
orbs:
  hugo: circleci/hugo@0.3.1

workflows:
  main:
    jobs:
      - hugo/build:
          source: /
          html-proofer: true
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master

jobs:
  deploy:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install curl -qy

      - run:
          name: Generate Static Content
          command: hugo

      - run:
          name: Deploy
          command: cd public && find . -type f -exec curl -u ${username}:${password} ${ssl} --ssl-reqd --ftp-create-dirs -T {} ftp://${host}/{} \;
