version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Checkout Submodules if Needed
          command: |
            if [ -f ".gitmodules" ]; then
              git submodule sync
              git submodule update --init --recursive
            fi
      - run:
          name: Install Hugo
          command: apt-get update && apt-get install curl  -qy

      - run:
          name: Generate Static Content
          command: hugo

      - run:
          name: Deploy
          command: cd public && find . -type f -exec curl -u ${username}:${password} ${ssl} --ssl-reqd --ftp-create-dirs -T {} ftp://${host}/{} \;
